In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../../data/AloQuote_wide.csv', index_col=0)
df.shape

(401, 169)

In [3]:
df

,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,...,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31
1001,12.7,12.2,12.5,12.3,11.7,11.2,10.8,10.7,11.6,11.5,...,9.6,9.1,8.7,8.7,8.8,9.4,9.2,9.1,9.1,8.9
1002,12.4,12.1,12.5,12.8,12.1,11.7,11.4,11.4,11.9,12.0,...,9.2,8.9,8.7,8.4,8.3,8.7,8.7,8.6,8.7,8.3
1003,12.8,12.7,12.9,12.9,12.7,12.4,12.3,12.4,12.8,12.7,...,8.6,8.3,8.2,8.1,8.2,8.7,8.8,8.9,8.9,8.6
1004,11.1,11.2,11.6,11.5,10.9,10.9,10.7,10.8,11.4,11.1,...,9.4,9.3,9.2,9.1,9.1,9.5,9.8,9.6,9.4,9.1
1051,9.9,9.5,9.7,9.7,9.0,8.8,9.2,9.6,10.7,10.6,...,6.2,5.8,5.7,5.8,6.2,6.8,6.9,6.6,6.4,6.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16073,13.1,12.6,12.2,12.1,11.3,11.0,11.1,11.5,12.7,12.6,...,6.0,5.8,5.8,5.7,5.9,6.5,6.6,6.5,6.3,6.0
16074,11.2,10.6,10.3,10.4,10.1,9.8,9.3,9.9,11.6,11.3,...,4.8,4.5,4.5,4.3,4.5,5.0,5.1,5.0,4.7,4.6
16075,10.9,9.9,10.0,10.0,9.3,9.1,9.1,9.9,11.4,11.3,...,5.1,4.8,4.6,4.7,4.9,5.5,5.5,5.3,5.0,4.8
16076,13.1,12.5,12.5,12.5,11.7,11.2,11.0,11.8,13.4,13.1,...,5.5,5.3,5.1,5.0,5.0,5.6,5.6,5.4,5.1,4.9
16077,18.1,17.3,17.1,17.3,16.9,16.3,16.2,16.5,18.1,18.1,...,7.3,7.0,6.8,6.8,6.7,7.3,7.3,7.2,6.9,6.7

In [18]:
df[df.columns[10:20]]

,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31
1001,11.4,11.4,11.4,11.0,11.4,11.8,11.4,11.1,11.3,11.6
1002,11.9,11.8,11.6,11.1,11.3,11.5,11.0,10.7,10.5,10.3
1003,12.6,12.5,12.4,12.1,12.3,12.3,11.8,11.6,11.5,11.7
1004,10.9,11.1,10.8,10.4,10.7,11.0,10.7,10.5,10.5,10.6
1051,10.2,9.6,9.3,9.0,9.4,9.6,9.3,9.0,9.2,9.7
...,...,...,...,...,...,...,...,...,...,...
16073,12.3,11.8,11.6,10.9,10.5,10.2,9.6,9.3,9.4,9.9
16074,10.8,9.8,9.1,8.4,8.3,8.3,8.1,8.1,8.0,9.2
16075,11.0,10.3,9.7,9.1,9.0,8.9,8.1,7.7,8.1,8.7
16076,12.4,11.6,11.0,10.5,11.2,11.1,10.4,10.2,10.0,11.1
16077,17.4,16.7,16.1,15.6,15.8,15.8,14.9,14.5,13.9,14.8